[phases.setup]
nixPkgs = ["nodejs", "python39"]

[phases.install]
cmds = [
  "cd frontend && npm install",
  "cd backend && pip3 install -r requirements.txt"
]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "cd backend && flask db upgrade && gunicorn app:app"
