providers = ['python', 'node']

[phases.setup]
nixPkgs = ['...']

[phases.install]
cmds = ["cd frontend && npm install"]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "cd backend && python -m flask db upgrade && gunicorn app:app"
