"""Add created_by field to Expense model

Revision ID: 1cc3ea55c1dd
Revises: 84096638b3d5
Create Date: 2025-11-11 16:35:18.703441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cc3ea55c1dd'
down_revision = '84096638b3d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        # Add column as nullable first
        batch_op.add_column(sa.Column('created_by', sa.String(length=50), nullable=True))

    # Set default value for existing rows (use 'user1' as default creator)
    op.execute("UPDATE expenses SET created_by = 'user1' WHERE created_by IS NULL")

    # Make the column NOT NULL
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('created_by', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
