"""Add expense_date field to Expense model

Revision ID: 28beeb1aea47
Revises: 35556d3b8bb5
Create Date: 2025-11-10 14:05:56.379645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28beeb1aea47'
down_revision = '35556d3b8bb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expense_date', sa.Date(), nullable=True))

    # Set default value for existing rows (today's date)
    from datetime import date
    op.execute(f"UPDATE expenses SET expense_date = '{date.today().isoformat()}' WHERE expense_date IS NULL")

    # Make column non-nullable
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('expense_date', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('expense_date')

    # ### end Alembic commands ###
