"""Make description field optional

Revision ID: 84096638b3d5
Revises: 28beeb1aea47
Create Date: 2025-11-11 16:00:52.083780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84096638b3d5'
down_revision = '28beeb1aea47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###
