"""Add Budget model for rolling monthly budgets

Revision ID: 877f6f6427d6
Revises: 1cc3ea55c1dd
Create Date: 2025-11-12 12:01:32.519558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '877f6f6427d6'
down_revision = '1cc3ea55c1dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=50), nullable=True),
    sa.Column('monthly_amount', sa.Float(), nullable=False),
    sa.Column('cumulative_balance', sa.Float(), nullable=True),
    sa.Column('last_updated_month', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'user', name='unique_category_user_budget')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('budgets')
    # ### end Alembic commands ###
