"""Add MonthlyBudgetSnapshot and remove cumulative fields from Budget

Revision ID: 996ebc58631a
Revises: 877f6f6427d6
Create Date: 2025-11-23 16:33:46.163486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '996ebc58631a'
down_revision = '877f6f6427d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_budget_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=50), nullable=True),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('monthly_amount', sa.Float(), nullable=False),
    sa.Column('carried_surplus', sa.Float(), nullable=True),
    sa.Column('carried_deficit', sa.Float(), nullable=True),
    sa.Column('actual_spent', sa.Float(), nullable=False),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'user', 'month', name='unique_category_user_month_snapshot')
    )

    # Data migration: Convert existing Budget records to MonthlyBudgetSnapshots
    # This will create snapshots for all past months based on existing expense data
    from datetime import datetime
    from dateutil.relativedelta import relativedelta

    conn = op.get_bind()

    # Get all budgets with their cumulative_balance and last_updated_month
    budgets = conn.execute(sa.text(
        "SELECT id, category_id, user, monthly_amount, cumulative_balance, last_updated_month FROM budgets"
    )).fetchall()

    # Get all expenses to calculate historical spending
    expenses = conn.execute(sa.text(
        "SELECT id, amount, category_id, created_by, expense_date FROM expenses ORDER BY expense_date"
    )).fetchall()

    # Get current system month
    current_month_str = datetime.utcnow().strftime('%Y-%m')

    # For each budget, create snapshots for all past months
    for budget in budgets:
        budget_id, category_id, user, monthly_amount, cumulative_balance, last_updated_month = budget

        # Skip if no expenses exist yet for this budget
        relevant_expenses = [
            e for e in expenses
            if e[2] == category_id and (user is None or e[3] == user)
        ]

        if not relevant_expenses and last_updated_month >= current_month_str:
            # No expenses and budget is current, skip creating snapshots
            continue

        # Find first expense date for this budget
        first_expense_date = min(e[4] for e in relevant_expenses) if relevant_expenses else last_updated_month + '-01'
        first_month = first_expense_date[:7]  # Extract YYYY-MM

        # Create snapshots from first month to last_updated_month (exclusive of current month)
        current_date = datetime.strptime(first_month, '%Y-%m')
        end_date = datetime.strptime(last_updated_month, '%Y-%m')

        running_balance = 0  # Start with zero balance

        while current_date <= end_date and current_date.strftime('%Y-%m') < current_month_str:
            month_str = current_date.strftime('%Y-%m')
            month_start = current_date.replace(day=1).strftime('%Y-%m-%d')
            next_month = current_date + relativedelta(months=1)
            month_end = next_month.replace(day=1).strftime('%Y-%m-%d')

            # Calculate spending for this month
            month_expenses = [
                e for e in relevant_expenses
                if e[4] >= month_start and e[4] < month_end
            ]
            month_spent = sum(e[1] for e in month_expenses)

            # Determine carried surplus/deficit from running balance
            carried_surplus = max(0, running_balance)
            carried_deficit = max(0, -running_balance)

            # Insert snapshot
            conn.execute(sa.text(
                """INSERT INTO monthly_budget_snapshots
                   (category_id, user, month, monthly_amount, carried_surplus, carried_deficit, actual_spent, finalized_at)
                   VALUES (:category_id, :user, :month, :monthly_amount, :carried_surplus, :carried_deficit, :actual_spent, :finalized_at)"""
            ), {
                'category_id': category_id,
                'user': user,
                'month': month_str,
                'monthly_amount': monthly_amount,
                'carried_surplus': carried_surplus,
                'carried_deficit': carried_deficit,
                'actual_spent': month_spent,
                'finalized_at': datetime.utcnow().isoformat()
            })

            # Update running balance for next month
            running_balance += (monthly_amount - month_spent)

            # Move to next month
            current_date = next_month

    # Now drop the old columns
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_column('last_updated_month')
        batch_op.drop_column('cumulative_balance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cumulative_balance', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('last_updated_month', sa.VARCHAR(length=7), nullable=False))

    op.drop_table('monthly_budget_snapshots')
    # ### end Alembic commands ###
